name: Build libraries

on:
  workflow_dispatch:
  workflow_call:
#  push:
#    branches:
#      - main
#      - fix-workflows
#  pull_request:
#  workflow_dispatch: # Allow manual trigger
#    inputs:
#      forcePublish:
#        description: 'Force publish snapshots of libraries to Artifactory even if not main branch'
#        type: boolean
#        default: 'false' # boolean values are actually strings
#        required: false

jobs:
  build:
    runs-on: self-hosted
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

#      - name: Set up Gradle
#        uses: gradle/actions/setup-gradle@v4
#        with:
#          gradle-version: '7.2'

      - name: Set env vars from AWS params
        uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        with:
          params: |
            SONAR_HOST_URL=/sonarqube/url
            SONAR_TOKEN=/sonarqube/token

      - name: Build and test libraries
        run: ./gradlew clean test --info -b build.gradle

      - name: Build JARs
        run: ./gradlew jar --info -b build.gradle

      - name: SonarQube Analysis
        run: |
          ./gradlew sonar \
            -Dsonar.projectKey=ab2d-lib-project \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      - name: Quality Gate
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: build/sonar/report-task.txt
        timeout-minutes: 10