name: Publish libraries

on:
  workflow_call:
    inputs:
      forcePublish:
        type: boolean
        default: false
        required: true
  workflow_dispatch:
    inputs:
      forcePublish:
        description: 'Force publish libraries to Artifactory - Use with caution as this may overwrite artifacts'
        type: boolean
        default: false
        required: false

env:
  ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  publish:
    permissions:
      contents: read
      id-token: write
    runs-on: codebuild-AB2D-Libs-${{ github.run_id }}-${{ github.run_attempt }}
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      FORCE_PUBLISH: ${{ inputs.forcePublish }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set env vars from AWS params
        uses: cmsgov/cdap/actions/aws-params-env-action@main
        with:
          params: |
            ARTIFACTORY_URL=/artifactory/url
            ARTIFACTORY_USER=/artifactory/user
            ARTIFACTORY_PASSWORD=/artifactory/password

      - name: Publish to artifactory
        run:  ./gradlew ab2d-contracts-client:artifactoryPublish -b build.gradle



