name: Publish Libraries

on:
  push:
    branches:
      #      - main
      - fix-workflows
  #  pull_request:
  workflow_call:
    inputs:
      forcePublish:
        type: boolean
        required: true
  workflow_dispatch: # Allow manual trigger
    inputs:
      forcePublish:
        description: 'Force publish snapshots of libraries to Artifactory even if not main branch'
        type: boolean
        default: 'false' # boolean values are actually strings
        required: false

env:
  ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}

jobs:
#  build:
#    uses: ./.github/workflows/build.yml
#    secrets: inherit
  publish:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set env vars from AWS params
        uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        with:
          params: |
            ARTIFACTORY_URL=/artifactory/url
            ARTIFACTORY_USER=/artifactory/user
            ARTIFACTORY_PASSWORD=/artifactory/password

      - name: Generate SBOM
        run: ./gradlew cyclonedxBom






      - name: Publish libraries from main branch
#        if: github.ref == 'refs/heads/main' && inputs.forcePublish != 'true'
        run: |
#                    Check for artifacts to deploy
               versionPublishedList=$(SUPPRESS_LOGGING_BRANCH_CLASSIFIER=true ./gradlew -q lookForArtifacts)

               deployScript=""
               for entry in $(echo "$versionPublishedList" | tr "'''" "\n"); do
               buildName=$(echo "$entry" | cut -d":" -f1)
               isPublished=$(echo "$entry" | cut -d":" -f2)

               if [ "$isPublished" == "false" ]; then
               echo "Deploying $buildName"
               deployScript+="$buildName:artifactoryPublish "
               fi
               done

               if [ "$deployScript" != "" ]; then
#                      ./gradlew  $deployScript -b build.gradle
               echo "*** (TEST) $deployScript"
               else
               echo "No artifacts to publish."
               fi

      - name: Force publish libraries
        if: inputs.forcePublish == 'true'
        #        run: ./gradlew  artifactoryPublish -b build.gradle
        run: echo "*** (TEST) Force publishing libraries"